spring:
  application:
    name: authentication
server:
  port: 8101

security:
  jwt:
    secret-key: MiClaveDeSeguridadMuyLargaParaQueNoFalleSpringBoot
    kit: cYz3kNRLAirxVhHXQ5rh5xKrOwHwZVui
    expiration:
      # Tiempo de validez para tokens para servicios (internos) 10min in seconds
      internal: 600
      # Tiempo de validez para tokens para usuarios (externos) 1h in seconds
      external: 3600

services:
  internal:
    users:
      url: http://localhost:8201/users